# Generated by Django 5.1.2 on 2024-11-05 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultexam',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
    ]
