# Generated by Django 5.1.2 on 2024-10-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Candidate'), (2, 'Teacher')], default=1),
        ),
    ]
